services:
  registration-service:
    build: ./registration-microservice
    container_name: registration-service
    ports:
      - "5003:5003"
    env_file:
      - ./registration-microservice/.env
    restart: unless-stopped

  login-service:
    build: ./login-microservice
    container_name: login-service
    ports:
      - "5004:5004"
    env_file:
      - ./login-microservice/.env
    restart: unless-stopped
